/*
Copyright (c) Anthony Beaumont
This source code is licensed under the Apache 2.0 License
found in the LICENSE file in the root directory of this source tree.
*/

//⚠️ This file was auto generated

import { load, reference } from "../../util/load.js";

const namespace = {
  //📖 https://learn.microsoft.com/en-us/uwp/api/windows.ui.webui
  name: "windows.ui.webui",
  externalReference: [
    "Windows.ApplicationModel.Background",
    "Windows.Foundation",
    "Windows.ApplicationModel.Activation",
    "Windows.ApplicationModel",
    "Windows.ApplicationModel.Core",
    "Windows.System",
    "Windows.ApplicationModel.Appointments.AppointmentsProvider",
    "Windows.Storage.Provider",
    "Windows.ApplicationModel.Contacts",
    "Windows.ApplicationModel.Contacts.Provider",
    "Windows.Devices.Enumeration",
    "Windows.Storage",
    "Windows.Storage.Search",
    "Windows.Storage.Pickers.Provider",
    "Windows.ApplicationModel.Calls",
    "Windows.Devices.Printers.Extensions",
    "Windows.ApplicationModel.Search",
    "Windows.ApplicationModel.DataTransfer.ShareTarget",
    "Windows.ApplicationModel.UserDataAccounts.Provider",
    "Windows.Web.UI",
    "Windows.Storage.Streams",
    "Windows.ApplicationModel.DataTransfer",
    "Windows.Web",
    "Windows.Web.Http",
    "Windows.Media.SpeechRecognition",
    "Windows.ApplicationModel.Wallet",
    "Windows.Security.Authentication.Web.Provider",
    "Windows.Security.Authentication.Web",
  ]
};

export const {
  PrintContent,
  ActivatedDeferral,
  ActivatedOperation,
  BackgroundActivatedEventArgs,
  EnteredBackgroundEventArgs,
  HtmlPrintDocumentSource,
  IActivatedEventArgsDeferral,
  IWebUIBackgroundTaskInstance,
  IWebUINavigatedEventArgs,
  LeavingBackgroundEventArgs,
  NewWebUIViewCreatedEventArgs,
  SuspendingDeferral,
  SuspendingEventArgs,
  SuspendingOperation,
  WebUIApplication,
  WebUIAppointmentsProviderAddAppointmentActivatedEventArgs,
  WebUIAppointmentsProviderRemoveAppointmentActivatedEventArgs,
  WebUIAppointmentsProviderReplaceAppointmentActivatedEventArgs,
  WebUIAppointmentsProviderShowAppointmentDetailsActivatedEventArgs,
  WebUIAppointmentsProviderShowTimeFrameActivatedEventArgs,
  WebUIBackgroundTaskInstance,
  WebUIBackgroundTaskInstanceRuntimeClass,
  WebUIBarcodeScannerPreviewActivatedEventArgs,
  WebUICachedFileUpdaterActivatedEventArgs,
  WebUICameraSettingsActivatedEventArgs,
  WebUICommandLineActivatedEventArgs,
  WebUIContactCallActivatedEventArgs,
  WebUIContactMapActivatedEventArgs,
  WebUIContactMessageActivatedEventArgs,
  WebUIContactPanelActivatedEventArgs,
  WebUIContactPickerActivatedEventArgs,
  WebUIContactPostActivatedEventArgs,
  WebUIContactVideoCallActivatedEventArgs,
  WebUIDeviceActivatedEventArgs,
  WebUIDevicePairingActivatedEventArgs,
  WebUIDialReceiverActivatedEventArgs,
  WebUIFileActivatedEventArgs,
  WebUIFileOpenPickerActivatedEventArgs,
  WebUIFileOpenPickerContinuationEventArgs,
  WebUIFileSavePickerActivatedEventArgs,
  WebUIFileSavePickerContinuationEventArgs,
  WebUIFolderPickerContinuationEventArgs,
  WebUILaunchActivatedEventArgs,
  WebUILockScreenActivatedEventArgs,
  WebUILockScreenCallActivatedEventArgs,
  WebUILockScreenComponentActivatedEventArgs,
  WebUINavigatedDeferral,
  WebUINavigatedEventArgs,
  WebUINavigatedOperation,
  WebUIPhoneCallActivatedEventArgs,
  WebUIPrint3DWorkflowActivatedEventArgs,
  WebUIPrintTaskSettingsActivatedEventArgs,
  WebUIPrintWorkflowForegroundTaskActivatedEventArgs,
  WebUIProtocolActivatedEventArgs,
  WebUIProtocolForResultsActivatedEventArgs,
  WebUIRestrictedLaunchActivatedEventArgs,
  WebUISearchActivatedEventArgs,
  WebUIShareTargetActivatedEventArgs,
  WebUIStartupTaskActivatedEventArgs,
  WebUIToastNotificationActivatedEventArgs,
  WebUIUserDataAccountProviderActivatedEventArgs,
  WebUIView,
  WebUIVoiceCommandActivatedEventArgs,
  WebUIWalletActionActivatedEventArgs,
  WebUIWebAccountProviderActivatedEventArgs,
  WebUIWebAuthenticationBrokerContinuationEventArgs,
} = load(namespace.name);

reference(namespace.externalReference);

export * as core from "./ui.webui.core.js";