/*
Copyright (c) Anthony Beaumont
This source code is licensed under the Apache 2.0 License
found in the LICENSE file in the root directory of this source tree.
*/

//⚠️ This file was auto generated

import { load, reference } from "../../util/load.js";

const namespace = {
  //📖 https://learn.microsoft.com/en-us/uwp/api/windows.media.core
  name: "windows.media.core",
  externalReference: [
    "Windows.Storage.Streams",
    "Windows.Graphics.Imaging",
    "Windows.Media.MediaProperties",
    "Windows.Media.Protection",
    "Windows.Storage.FileProperties",
    "Windows.ApplicationModel.AppService",
    "Windows.Foundation",
    "Windows.Media.Devices.Core",
    "Windows.Media.Capture",
    "Windows.Media.FaceAnalysis",
    "Windows.Media.Devices",
    "Windows.Media.Streaming.Adaptive",
    "Windows.Networking.BackgroundTransfer",
    "Windows.Media.Capture.Frames",
    "Windows.Storage",
    "Windows.Media.Playback",
  ]
};

export const {
  TimedTextScrollMode,
  TimedTextUnit,
  TimedTextWritingMode,
  TimedTextDisplayAlignment,
  TimedTextLineAlignment,
  TimedTextWrapping,
  TimedTextWeight,
  TimedTextFlowDirection,
  TimedTextFontStyle,
  CodecKind,
  CodecCategory,
  MediaStreamSourceClosedReason,
  MediaStreamSourceErrorStatus,
  MseReadyState,
  MseEndOfStreamStatus,
  MseAppendMode,
  SceneAnalysisRecommendation,
  FaceDetectionMode,
  VideoStabilizationEffectEnabledChangedReason,
  MediaTrackKind,
  TimedMetadataKind,
  TimedMetadataTrackErrorCode,
  MediaDecoderStatus,
  AudioDecoderDegradation,
  AudioDecoderDegradationReason,
  MediaSourceStatus,
  MediaSourceState,
  IMediaCue,
  TimedTextRegion,
  TimedTextStyle,
  TimedTextLine,
  TimedTextSubformat,
  TimedTextCue,
  DataCue,
  ChapterCue,
  ImageCue,
  SpeechCue,
  CodecInfo,
  CodecQuery,
  CodecSubtypes,
  LowLightFusionResult,
  LowLightFusion,
  AudioStreamDescriptor,
  VideoStreamDescriptor,
  TimedMetadataStreamDescriptor,
  IMediaStreamDescriptor,
  IMediaStreamDescriptor2,
  IMediaSource,
  MediaStreamSource,
  MediaStreamSourceClosedEventArgs,
  MediaStreamSourceStartingEventArgs,
  MediaStreamSourceSampleRequestedEventArgs,
  MediaStreamSourceSwitchStreamsRequestedEventArgs,
  MediaStreamSourceSampleRenderedEventArgs,
  MediaStreamSamplePropertySet,
  MediaStreamSample,
  MediaStreamSampleProtectionProperties,
  MediaStreamSourceClosedRequest,
  MediaStreamSourceStartingRequestDeferral,
  MediaStreamSourceStartingRequest,
  MediaStreamSourceSampleRequestDeferral,
  MediaStreamSourceSampleRequest,
  MediaStreamSourceSwitchStreamsRequestDeferral,
  MediaStreamSourceSwitchStreamsRequest,
  MseStreamSource,
  MseSourceBufferList,
  MseSourceBuffer,
  MediaSourceAppServiceConnection,
  InitializeMediaStreamSourceRequestedEventArgs,
  HighDynamicRangeControl,
  SceneAnalysisEffect,
  SceneAnalyzedEventArgs,
  HighDynamicRangeOutput,
  SceneAnalysisEffectFrame,
  SceneAnalysisEffectDefinition,
  FaceDetectionEffectFrame,
  FaceDetectedEventArgs,
  FaceDetectionEffect,
  FaceDetectionEffectDefinition,
  VideoStabilizationEffectEnabledChangedEventArgs,
  VideoStabilizationEffect,
  VideoStabilizationEffectDefinition,
  MediaSourceError,
  MediaSource,
  MediaBinder,
  MediaBindingEventArgs,
  MediaSourceOpenOperationCompletedEventArgs,
  TimedTextSource,
  TimedMetadataTrack,
  MediaSourceStateChangedEventArgs,
  ISingleSelectMediaTrackList,
  IMediaTrack,
  TimedMetadataTrackError,
  ITimedMetadataTrackProvider,
  MediaCueEventArgs,
  TimedMetadataTrackFailedEventArgs,
  TimedTextSourceResolveResultEventArgs,
  VideoTrack,
  VideoTrackOpenFailedEventArgs,
  VideoTrackSupportInfo,
  AudioTrack,
  AudioTrackOpenFailedEventArgs,
  AudioTrackSupportInfo,
} = load(namespace.name);

reference(namespace.externalReference);

export * as preview from "./media.core.preview.js";