/*
Copyright (c) Anthony Beaumont
This source code is licensed under the Apache 2.0 License
found in the LICENSE file in the root directory of this source tree.
*/

//⚠️ This file was auto generated

import { load, reference } from "../../util/load.js";

const namespace = {
  //📖 https://learn.microsoft.com/en-us/uwp/api/windows.media.capture
  name: "windows.media.capture",
  externalReference: [
    "Windows.Foundation",
    "Windows.Storage",
    "Windows.Media.Devices",
    "Windows.Media.Capture.Frames",
    "Windows.Media",
    "Windows.Media.MediaProperties",
    "Windows.Storage.Streams",
    "Windows.Media.Capture.Core",
    "Windows.Media.Effects",
    "Windows.Media.Core",
    "Windows.Graphics.DirectX.Direct3D11",
    "Windows.Graphics.Imaging",
    "Windows.Security.Authentication.Web",
    "Windows.System",
  ]
};

export const {
  CameraCaptureUIMode,
  CameraCaptureUIPhotoFormat,
  CameraCaptureUIVideoFormat,
  CameraCaptureUIMaxVideoResolution,
  CameraCaptureUIMaxPhotoResolution,
  MediaCategory,
  StreamingCaptureMode,
  VideoRotation,
  PhotoCaptureSource,
  VideoDeviceCharacteristic,
  MediaCaptureThermalStatus,
  MediaCaptureDeviceExclusiveControlStatus,
  KnownVideoProfile,
  MediaCaptureMemoryPreference,
  MediaCaptureSharingMode,
  MediaStreamType,
  PowerlineFrequency,
  AppBroadcastCameraOverlayLocation,
  AppBroadcastCameraOverlaySize,
  AppBroadcastVideoEncodingBitrateMode,
  AppBroadcastVideoEncodingResolutionMode,
  AppBroadcastPlugInState,
  AppBroadcastStreamState,
  AppBroadcastSignInState,
  AppBroadcastTerminationReason,
  AppBroadcastSignInResult,
  ForegroundActivationArgument,
  AppBroadcastMicrophoneCaptureState,
  AppBroadcastCameraCaptureState,
  AppBroadcastExitBroadcastModeReason,
  AppBroadcastPreviewState,
  AppBroadcastCaptureTargetType,
  GameBarServicesDisplayMode,
  AppCaptureVideoEncodingBitrateMode,
  AppCaptureVideoEncodingResolutionMode,
  AppCaptureVideoEncodingFrameRateMode,
  AppCaptureHistoricalBufferLengthUnit,
  AppCaptureMicrophoneCaptureState,
  AppCaptureRecordingState,
  AppCaptureMetadataPriority,
  GameBarCommand,
  GameBarCommandOrigin,
  GameBarTargetCapturePolicy,
  AppCapture,
  CameraCaptureUIPhotoCaptureSettings,
  CameraCaptureUIVideoCaptureSettings,
  CameraCaptureUI,
  MediaCaptureFailedEventArgs,
  MediaCapture,
  MediaCaptureVideoProfileMediaDescription,
  MediaCaptureVideoProfile,
  MediaCaptureInitializationSettings,
  MediaCaptureSettings,
  LowLagMediaRecording,
  LowLagPhotoCapture,
  LowLagPhotoSequenceCapture,
  MediaCaptureFocusChangedEventArgs,
  PhotoConfirmationCapturedEventArgs,
  AdvancedPhotoCapture,
  MediaCapturePauseResult,
  MediaCaptureStopResult,
  MediaCaptureDeviceExclusiveControlStatusChangedEventArgs,
  CapturedPhoto,
  AdvancedCapturedPhoto,
  OptionalReferencePhotoCapturedEventArgs,
  CapturedFrame,
  PhotoCapturedEventArgs,
  CapturedFrameControlValues,
  VideoStreamConfiguration,
  AppBroadcastGlobalSettings,
  AppBroadcastProviderSettings,
  AppBroadcastManager,
  AppBroadcastBackgroundServiceSignInInfo,
  AppBroadcastSignInStateChangedEventArgs,
  AppBroadcastStreamReader,
  AppBroadcastBackgroundServiceStreamInfo,
  AppBroadcastStreamStateChangedEventArgs,
  AppBroadcastBackgroundService,
  AppBroadcastHeartbeatRequestedEventArgs,
  AppBroadcastStreamAudioFrame,
  AppBroadcastStreamVideoFrame,
  AppBroadcastStreamVideoHeader,
  AppBroadcastStreamAudioHeader,
  AppBroadcastTriggerDetails,
  AppBroadcastPlugInManager,
  AppBroadcastPlugIn,
  AppBroadcastPreview,
  AppBroadcastState,
  AppBroadcastViewerCountChangedEventArgs,
  AppBroadcastMicrophoneCaptureStateChangedEventArgs,
  AppBroadcastCameraCaptureStateChangedEventArgs,
  AppBroadcastPlugInStateChangedEventArgs,
  AppBroadcastPreviewStateChangedEventArgs,
  AppBroadcastPreviewStreamReader,
  AppBroadcastPreviewStreamVideoFrame,
  AppBroadcastPreviewStreamVideoHeader,
  AppBroadcastServices,
  AppCaptureSettings,
  AppCaptureAlternateShortcutKeys,
  AppCaptureManager,
  AppCaptureRecordOperation,
  AppCaptureState,
  AppCaptureMicrophoneCaptureStateChangedEventArgs,
  AppCaptureRecordingStateChangedEventArgs,
  AppCaptureDurationGeneratedEventArgs,
  AppCaptureFileGeneratedEventArgs,
  AppCaptureServices,
  AppCaptureMetadataWriter,
  CameraOptionsUI,
  GameBarServicesManager,
  GameBarServicesManagerGameBarServicesCreatedEventArgs,
  GameBarServices,
  GameBarServicesTargetInfo,
  GameBarServicesCommandEventArgs,
  ScreenCapture,
  SourceSuspensionChangedEventArgs,
} = load(namespace.name);

reference(namespace.externalReference);

export * as core from "./media.capture.core.js";
export * as frames from "./media.capture.frames.js";