/*
Copyright (c) Anthony Beaumont
This source code is licensed under the Apache 2.0 License
found in the LICENSE file in the root directory of this source tree.
*/

//⚠️ This file was auto generated

import { load, reference } from "../../util/load.js";

const namespace = {
  //📖 https://learn.microsoft.com/en-us/uwp/api/windows.media.capture
  name: "windows.media.capture",
  externalReference: [
    "Windows.Media.Devices",
    "Windows.Foundation",
    "Windows.Security.Authentication.Web",
    "Windows.Storage.Streams",
    "Windows.System",
    "Windows.Graphics.Imaging",
    "Windows.Storage",
    "Windows.Media.MediaProperties",
    "Windows.Media.Capture.Frames",
    "Windows.Media",
    "Windows.Media.Capture.Core",
    "Windows.Media.Effects",
    "Windows.UI.WindowManagement",
    "Windows.Media.Core",
    "Windows.Security.Credentials",
    "Windows.Devices.Enumeration",
    "Windows.Graphics.DirectX.Direct3D11",
  ]
};

export const {
  AppBroadcastCameraCaptureState,
  AppBroadcastCameraOverlayLocation,
  AppBroadcastCameraOverlaySize,
  AppBroadcastCaptureTargetType,
  AppBroadcastExitBroadcastModeReason,
  AppBroadcastMicrophoneCaptureState,
  AppBroadcastPlugInState,
  AppBroadcastPreviewState,
  AppBroadcastSignInResult,
  AppBroadcastSignInState,
  AppBroadcastStreamState,
  AppBroadcastTerminationReason,
  AppBroadcastVideoEncodingBitrateMode,
  AppBroadcastVideoEncodingResolutionMode,
  AppCaptureHistoricalBufferLengthUnit,
  AppCaptureMetadataPriority,
  AppCaptureMicrophoneCaptureState,
  AppCaptureRecordingState,
  AppCaptureVideoEncodingBitrateMode,
  AppCaptureVideoEncodingFrameRateMode,
  AppCaptureVideoEncodingResolutionMode,
  CameraCaptureUIMaxPhotoResolution,
  CameraCaptureUIMaxVideoResolution,
  CameraCaptureUIMode,
  CameraCaptureUIPhotoFormat,
  CameraCaptureUIVideoFormat,
  ForegroundActivationArgument,
  GameBarCommand,
  GameBarCommandOrigin,
  GameBarServicesDisplayMode,
  GameBarTargetCapturePolicy,
  KnownVideoProfile,
  MediaCaptureDeviceExclusiveControlReleaseMode,
  MediaCaptureDeviceExclusiveControlStatus,
  MediaCaptureMemoryPreference,
  MediaCaptureSharingMode,
  MediaCaptureThermalStatus,
  MediaCategory,
  MediaStreamType,
  PhotoCaptureSource,
  PowerlineFrequency,
  StreamingCaptureMode,
  VideoDeviceCharacteristic,
  VideoRotation,
  AdvancedCapturedPhoto,
  AdvancedPhotoCapture,
  AppBroadcastBackgroundService,
  AppBroadcastBackgroundServiceSignInInfo,
  AppBroadcastBackgroundServiceStreamInfo,
  AppBroadcastCameraCaptureStateChangedEventArgs,
  AppBroadcastGlobalSettings,
  AppBroadcastHeartbeatRequestedEventArgs,
  AppBroadcastManager,
  AppBroadcastMicrophoneCaptureStateChangedEventArgs,
  AppBroadcastPlugIn,
  AppBroadcastPlugInManager,
  AppBroadcastPlugInStateChangedEventArgs,
  AppBroadcastPreview,
  AppBroadcastPreviewStateChangedEventArgs,
  AppBroadcastPreviewStreamReader,
  AppBroadcastPreviewStreamVideoFrame,
  AppBroadcastPreviewStreamVideoHeader,
  AppBroadcastProviderSettings,
  AppBroadcastServices,
  AppBroadcastSignInStateChangedEventArgs,
  AppBroadcastState,
  AppBroadcastStreamAudioFrame,
  AppBroadcastStreamAudioHeader,
  AppBroadcastStreamReader,
  AppBroadcastStreamStateChangedEventArgs,
  AppBroadcastStreamVideoFrame,
  AppBroadcastStreamVideoHeader,
  AppBroadcastTriggerDetails,
  AppBroadcastViewerCountChangedEventArgs,
  AppCapture,
  AppCaptureAlternateShortcutKeys,
  AppCaptureDurationGeneratedEventArgs,
  AppCaptureFileGeneratedEventArgs,
  AppCaptureManager,
  AppCaptureMetadataWriter,
  AppCaptureMicrophoneCaptureStateChangedEventArgs,
  AppCaptureRecordOperation,
  AppCaptureRecordingStateChangedEventArgs,
  AppCaptureServices,
  AppCaptureSettings,
  AppCaptureState,
  CameraCaptureUI,
  CameraCaptureUIPhotoCaptureSettings,
  CameraCaptureUIVideoCaptureSettings,
  CameraOptionsUI,
  CapturedFrame,
  CapturedFrameControlValues,
  CapturedPhoto,
  GameBarServices,
  GameBarServicesCommandEventArgs,
  GameBarServicesManager,
  GameBarServicesManagerGameBarServicesCreatedEventArgs,
  GameBarServicesTargetInfo,
  LowLagMediaRecording,
  LowLagPhotoCapture,
  LowLagPhotoSequenceCapture,
  MediaCapture,
  MediaCaptureDeviceExclusiveControlStatusChangedEventArgs,
  MediaCaptureFailedEventArgs,
  MediaCaptureFocusChangedEventArgs,
  MediaCaptureInitializationSettings,
  MediaCapturePauseResult,
  MediaCaptureRelativePanelWatcher,
  MediaCaptureSettings,
  MediaCaptureStopResult,
  MediaCaptureVideoProfile,
  MediaCaptureVideoProfileMediaDescription,
  OptionalReferencePhotoCapturedEventArgs,
  PhotoCapturedEventArgs,
  PhotoConfirmationCapturedEventArgs,
  ScreenCapture,
  SourceSuspensionChangedEventArgs,
  VideoStreamConfiguration,
} = load(namespace.name);

reference(namespace.externalReference);

export * as core from "./media.capture.core.js";
export * as frames from "./media.capture.frames.js";